/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TGeq extends Token
{
    public TGeq()
    {
        super.setText(">=");
    }

    public TGeq(int line, int pos)
    {
        super.setText(">=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGeq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGeq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGeq text.");
    }
}
