/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLeq extends Token
{
    public TLeq()
    {
        super.setText("<=");
    }

    public TLeq(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLeq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLeq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLeq text.");
    }
}
