/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TQmark extends Token
{
    public TQmark()
    {
        super.setText("?");
    }

    public TQmark(int line, int pos)
    {
        super.setText("?");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TQmark(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQmark(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TQmark text.");
    }
}
