/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ADivAssignAssignmentStatement extends PAssignmentStatement
{
    private TIdentifier _identifier_;
    private TDivAssign _divAssign_;
    private PExpression _expression_;

    public ADivAssignAssignmentStatement()
    {
    }

    public ADivAssignAssignmentStatement(
        TIdentifier _identifier_,
        TDivAssign _divAssign_,
        PExpression _expression_)
    {
        setIdentifier(_identifier_);

        setDivAssign(_divAssign_);

        setExpression(_expression_);

    }
    public Object clone()
    {
        return new ADivAssignAssignmentStatement(
            (TIdentifier) cloneNode(_identifier_),
            (TDivAssign) cloneNode(_divAssign_),
            (PExpression) cloneNode(_expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivAssignAssignmentStatement(this);
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public TDivAssign getDivAssign()
    {
        return _divAssign_;
    }

    public void setDivAssign(TDivAssign node)
    {
        if(_divAssign_ != null)
        {
            _divAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _divAssign_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_divAssign_)
            + toString(_expression_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_divAssign_ == child)
        {
            _divAssign_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_divAssign_ == oldChild)
        {
            setDivAssign((TDivAssign) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

    }
}
