/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ALeqClause extends PClause
{
    private PExpression _lhs_;
    private TLeq _leq_;
    private PExpression _rhs_;

    public ALeqClause()
    {
    }

    public ALeqClause(
        PExpression _lhs_,
        TLeq _leq_,
        PExpression _rhs_)
    {
        setLhs(_lhs_);

        setLeq(_leq_);

        setRhs(_rhs_);

    }
    public Object clone()
    {
        return new ALeqClause(
            (PExpression) cloneNode(_lhs_),
            (TLeq) cloneNode(_leq_),
            (PExpression) cloneNode(_rhs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeqClause(this);
    }

    public PExpression getLhs()
    {
        return _lhs_;
    }

    public void setLhs(PExpression node)
    {
        if(_lhs_ != null)
        {
            _lhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lhs_ = node;
    }

    public TLeq getLeq()
    {
        return _leq_;
    }

    public void setLeq(TLeq node)
    {
        if(_leq_ != null)
        {
            _leq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _leq_ = node;
    }

    public PExpression getRhs()
    {
        return _rhs_;
    }

    public void setRhs(PExpression node)
    {
        if(_rhs_ != null)
        {
            _rhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rhs_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lhs_)
            + toString(_leq_)
            + toString(_rhs_);
    }

    void removeChild(Node child)
    {
        if(_lhs_ == child)
        {
            _lhs_ = null;
            return;
        }

        if(_leq_ == child)
        {
            _leq_ = null;
            return;
        }

        if(_rhs_ == child)
        {
            _rhs_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lhs_ == oldChild)
        {
            setLhs((PExpression) newChild);
            return;
        }

        if(_leq_ == oldChild)
        {
            setLeq((TLeq) newChild);
            return;
        }

        if(_rhs_ == oldChild)
        {
            setRhs((PExpression) newChild);
            return;
        }

    }
}
