/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ALessClause extends PClause
{
    private PExpression _lhs_;
    private TLess _less_;
    private PExpression _rhs_;

    public ALessClause()
    {
    }

    public ALessClause(
        PExpression _lhs_,
        TLess _less_,
        PExpression _rhs_)
    {
        setLhs(_lhs_);

        setLess(_less_);

        setRhs(_rhs_);

    }
    public Object clone()
    {
        return new ALessClause(
            (PExpression) cloneNode(_lhs_),
            (TLess) cloneNode(_less_),
            (PExpression) cloneNode(_rhs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessClause(this);
    }

    public PExpression getLhs()
    {
        return _lhs_;
    }

    public void setLhs(PExpression node)
    {
        if(_lhs_ != null)
        {
            _lhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lhs_ = node;
    }

    public TLess getLess()
    {
        return _less_;
    }

    public void setLess(TLess node)
    {
        if(_less_ != null)
        {
            _less_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _less_ = node;
    }

    public PExpression getRhs()
    {
        return _rhs_;
    }

    public void setRhs(PExpression node)
    {
        if(_rhs_ != null)
        {
            _rhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rhs_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lhs_)
            + toString(_less_)
            + toString(_rhs_);
    }

    void removeChild(Node child)
    {
        if(_lhs_ == child)
        {
            _lhs_ = null;
            return;
        }

        if(_less_ == child)
        {
            _less_ = null;
            return;
        }

        if(_rhs_ == child)
        {
            _rhs_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lhs_ == oldChild)
        {
            setLhs((PExpression) newChild);
            return;
        }

        if(_less_ == oldChild)
        {
            setLess((TLess) newChild);
            return;
        }

        if(_rhs_ == oldChild)
        {
            setRhs((PExpression) newChild);
            return;
        }

    }
}
