/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AListDefFunc extends PFunc
{
    private TLBr _lBr_;
    private PExpression _expression_;
    private final LinkedList _commaExpression_ = new TypedLinkedList(new CommaExpression_Cast());
    private TRBr _rBr_;

    public AListDefFunc()
    {
    }

    public AListDefFunc(
        TLBr _lBr_,
        PExpression _expression_,
        List _commaExpression_,
        TRBr _rBr_)
    {
        setLBr(_lBr_);

        setExpression(_expression_);

        {
            this._commaExpression_.clear();
            this._commaExpression_.addAll(_commaExpression_);
        }

        setRBr(_rBr_);

    }
    public Object clone()
    {
        return new AListDefFunc(
            (TLBr) cloneNode(_lBr_),
            (PExpression) cloneNode(_expression_),
            cloneList(_commaExpression_),
            (TRBr) cloneNode(_rBr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListDefFunc(this);
    }

    public TLBr getLBr()
    {
        return _lBr_;
    }

    public void setLBr(TLBr node)
    {
        if(_lBr_ != null)
        {
            _lBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBr_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getCommaExpression()
    {
        return _commaExpression_;
    }

    public void setCommaExpression(List list)
    {
        _commaExpression_.clear();
        _commaExpression_.addAll(list);
    }

    public TRBr getRBr()
    {
        return _rBr_;
    }

    public void setRBr(TRBr node)
    {
        if(_rBr_ != null)
        {
            _rBr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBr_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lBr_)
            + toString(_expression_)
            + toString(_commaExpression_)
            + toString(_rBr_);
    }

    void removeChild(Node child)
    {
        if(_lBr_ == child)
        {
            _lBr_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_commaExpression_.remove(child))
        {
            return;
        }

        if(_rBr_ == child)
        {
            _rBr_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lBr_ == oldChild)
        {
            setLBr((TLBr) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _commaExpression_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_rBr_ == oldChild)
        {
            setRBr((TRBr) newChild);
            return;
        }

    }

    private class CommaExpression_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PCommaExpression node = (PCommaExpression) o;

            if((node.parent() != null) &&
                (node.parent() != AListDefFunc.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AListDefFunc.this))
            {
                node.parent(AListDefFunc.this);
            }

            return node;
        }
    }
}
