/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMinExpression extends PExpression
{
    private PValue _v1_;
    private final LinkedList _v2_ = new TypedLinkedList(new V2_Cast());

    public AMinExpression()
    {
    }

    public AMinExpression(
        PValue _v1_,
        List _v2_)
    {
        setV1(_v1_);

        {
            this._v2_.clear();
            this._v2_.addAll(_v2_);
        }

    }
    public Object clone()
    {
        return new AMinExpression(
            (PValue) cloneNode(_v1_),
            cloneList(_v2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinExpression(this);
    }

    public PValue getV1()
    {
        return _v1_;
    }

    public void setV1(PValue node)
    {
        if(_v1_ != null)
        {
            _v1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _v1_ = node;
    }

    public LinkedList getV2()
    {
        return _v2_;
    }

    public void setV2(List list)
    {
        _v2_.clear();
        _v2_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_v1_)
            + toString(_v2_);
    }

    void removeChild(Node child)
    {
        if(_v1_ == child)
        {
            _v1_ = null;
            return;
        }

        if(_v2_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_v1_ == oldChild)
        {
            setV1((PValue) newChild);
            return;
        }

        for(ListIterator i = _v2_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class V2_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PValue node = (PValue) o;

            if((node.parent() != null) &&
                (node.parent() != AMinExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AMinExpression.this))
            {
                node.parent(AMinExpression.this);
            }

            return node;
        }
    }
}
