/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMinusSum extends PSum
{
    private PSum _sum_;
    private TMinus _minus_;
    private PTerm _term_;

    public AMinusSum()
    {
    }

    public AMinusSum(
        PSum _sum_,
        TMinus _minus_,
        PTerm _term_)
    {
        setSum(_sum_);

        setMinus(_minus_);

        setTerm(_term_);

    }
    public Object clone()
    {
        return new AMinusSum(
            (PSum) cloneNode(_sum_),
            (TMinus) cloneNode(_minus_),
            (PTerm) cloneNode(_term_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusSum(this);
    }

    public PSum getSum()
    {
        return _sum_;
    }

    public void setSum(PSum node)
    {
        if(_sum_ != null)
        {
            _sum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _sum_ = node;
    }

    public TMinus getMinus()
    {
        return _minus_;
    }

    public void setMinus(TMinus node)
    {
        if(_minus_ != null)
        {
            _minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minus_ = node;
    }

    public PTerm getTerm()
    {
        return _term_;
    }

    public void setTerm(PTerm node)
    {
        if(_term_ != null)
        {
            _term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _term_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_sum_)
            + toString(_minus_)
            + toString(_term_);
    }

    void removeChild(Node child)
    {
        if(_sum_ == child)
        {
            _sum_ = null;
            return;
        }

        if(_minus_ == child)
        {
            _minus_ = null;
            return;
        }

        if(_term_ == child)
        {
            _term_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_sum_ == oldChild)
        {
            setSum((PSum) newChild);
            return;
        }

        if(_minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(_term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

    }
}
