/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMinusAssignAssignmentStatement extends PAssignmentStatement
{
    private TIdentifier _identifier_;
    private TMinusAssign _minusAssign_;
    private PExpression _expression_;

    public AMinusAssignAssignmentStatement()
    {
    }

    public AMinusAssignAssignmentStatement(
        TIdentifier _identifier_,
        TMinusAssign _minusAssign_,
        PExpression _expression_)
    {
        setIdentifier(_identifier_);

        setMinusAssign(_minusAssign_);

        setExpression(_expression_);

    }
    public Object clone()
    {
        return new AMinusAssignAssignmentStatement(
            (TIdentifier) cloneNode(_identifier_),
            (TMinusAssign) cloneNode(_minusAssign_),
            (PExpression) cloneNode(_expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMinusAssignAssignmentStatement(this);
    }

    public TIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public TMinusAssign getMinusAssign()
    {
        return _minusAssign_;
    }

    public void setMinusAssign(TMinusAssign node)
    {
        if(_minusAssign_ != null)
        {
            _minusAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minusAssign_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_minusAssign_)
            + toString(_expression_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_minusAssign_ == child)
        {
            _minusAssign_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(_minusAssign_ == oldChild)
        {
            setMinusAssign((TMinusAssign) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

    }
}
