/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ANeqClause extends PClause
{
    private PExpression _lhs_;
    private TNeq _neq_;
    private PExpression _rhs_;

    public ANeqClause()
    {
    }

    public ANeqClause(
        PExpression _lhs_,
        TNeq _neq_,
        PExpression _rhs_)
    {
        setLhs(_lhs_);

        setNeq(_neq_);

        setRhs(_rhs_);

    }
    public Object clone()
    {
        return new ANeqClause(
            (PExpression) cloneNode(_lhs_),
            (TNeq) cloneNode(_neq_),
            (PExpression) cloneNode(_rhs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeqClause(this);
    }

    public PExpression getLhs()
    {
        return _lhs_;
    }

    public void setLhs(PExpression node)
    {
        if(_lhs_ != null)
        {
            _lhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lhs_ = node;
    }

    public TNeq getNeq()
    {
        return _neq_;
    }

    public void setNeq(TNeq node)
    {
        if(_neq_ != null)
        {
            _neq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _neq_ = node;
    }

    public PExpression getRhs()
    {
        return _rhs_;
    }

    public void setRhs(PExpression node)
    {
        if(_rhs_ != null)
        {
            _rhs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rhs_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lhs_)
            + toString(_neq_)
            + toString(_rhs_);
    }

    void removeChild(Node child)
    {
        if(_lhs_ == child)
        {
            _lhs_ = null;
            return;
        }

        if(_neq_ == child)
        {
            _neq_ = null;
            return;
        }

        if(_rhs_ == child)
        {
            _rhs_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lhs_ == oldChild)
        {
            setLhs((PExpression) newChild);
            return;
        }

        if(_neq_ == oldChild)
        {
            setNeq((TNeq) newChild);
            return;
        }

        if(_rhs_ == oldChild)
        {
            setRhs((PExpression) newChild);
            return;
        }

    }
}
