/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AOrcCompT extends PCompT
{
    private TOr _or_;
    private PComparison _comparison_;
    private PCompT _compT_;

    public AOrcCompT()
    {
    }

    public AOrcCompT(
        TOr _or_,
        PComparison _comparison_,
        PCompT _compT_)
    {
        setOr(_or_);

        setComparison(_comparison_);

        setCompT(_compT_);

    }
    public Object clone()
    {
        return new AOrcCompT(
            (TOr) cloneNode(_or_),
            (PComparison) cloneNode(_comparison_),
            (PCompT) cloneNode(_compT_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrcCompT(this);
    }

    public TOr getOr()
    {
        return _or_;
    }

    public void setOr(TOr node)
    {
        if(_or_ != null)
        {
            _or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _or_ = node;
    }

    public PComparison getComparison()
    {
        return _comparison_;
    }

    public void setComparison(PComparison node)
    {
        if(_comparison_ != null)
        {
            _comparison_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparison_ = node;
    }

    public PCompT getCompT()
    {
        return _compT_;
    }

    public void setCompT(PCompT node)
    {
        if(_compT_ != null)
        {
            _compT_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _compT_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_or_)
            + toString(_comparison_)
            + toString(_compT_);
    }

    void removeChild(Node child)
    {
        if(_or_ == child)
        {
            _or_ = null;
            return;
        }

        if(_comparison_ == child)
        {
            _comparison_ = null;
            return;
        }

        if(_compT_ == child)
        {
            _compT_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(_comparison_ == oldChild)
        {
            setComparison((PComparison) newChild);
            return;
        }

        if(_compT_ == oldChild)
        {
            setCompT((PCompT) newChild);
            return;
        }

    }
}
