/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AOrDisjunction extends PDisjunction
{
    private PDisjunction _disjunction_;
    private TOr _or_;
    private PConjuction _conjuction_;

    public AOrDisjunction()
    {
    }

    public AOrDisjunction(
        PDisjunction _disjunction_,
        TOr _or_,
        PConjuction _conjuction_)
    {
        setDisjunction(_disjunction_);

        setOr(_or_);

        setConjuction(_conjuction_);

    }
    public Object clone()
    {
        return new AOrDisjunction(
            (PDisjunction) cloneNode(_disjunction_),
            (TOr) cloneNode(_or_),
            (PConjuction) cloneNode(_conjuction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrDisjunction(this);
    }

    public PDisjunction getDisjunction()
    {
        return _disjunction_;
    }

    public void setDisjunction(PDisjunction node)
    {
        if(_disjunction_ != null)
        {
            _disjunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _disjunction_ = node;
    }

    public TOr getOr()
    {
        return _or_;
    }

    public void setOr(TOr node)
    {
        if(_or_ != null)
        {
            _or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _or_ = node;
    }

    public PConjuction getConjuction()
    {
        return _conjuction_;
    }

    public void setConjuction(PConjuction node)
    {
        if(_conjuction_ != null)
        {
            _conjuction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _conjuction_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_disjunction_)
            + toString(_or_)
            + toString(_conjuction_);
    }

    void removeChild(Node child)
    {
        if(_disjunction_ == child)
        {
            _disjunction_ = null;
            return;
        }

        if(_or_ == child)
        {
            _or_ = null;
            return;
        }

        if(_conjuction_ == child)
        {
            _conjuction_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_disjunction_ == oldChild)
        {
            setDisjunction((PDisjunction) newChild);
            return;
        }

        if(_or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(_conjuction_ == oldChild)
        {
            setConjuction((PConjuction) newChild);
            return;
        }

    }
}
