/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.lexer;

import java.io.*;
import java.util.*;
import minipython.node.*;

public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    protected void filter() throws LexerException, IOException
    {
    }

    public Lexer(PushbackReader in)
    {
        this.in = in;

        if(gotoTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Lexer.class.getResourceAsStream("lexer.dat")));

                // read gotoTable
                int length = s.readInt();
                gotoTable = new int[length][][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][][];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        length = s.readInt();
                        gotoTable[i][j] = new int[length][3];
                        for(int k = 0; k < gotoTable[i][j].length; k++)
                        {
                            for(int l = 0; l < 3; l++)
                            {
                                gotoTable[i][j][k][l] = s.readInt();
                            }
                        }
                    }
                }

                // read accept
                length = s.readInt();
                accept = new int[length][];
                for(int i = 0; i < accept.length; i++)
                {
                    length = s.readInt();
                    accept[i] = new int[length];
                    for(int j = 0; j < accept[i].length; j++)
                    {
                        accept[i][j] = s.readInt();
                    }
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
            }
        }
    }

    public Token peek() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        return token;
    }

    public Token next() throws LexerException, IOException
    {
        while(token == null)
        {
            token = getToken();
            filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = this.gotoTable[state.id()];
        int[] accept = this.accept[state.id()];
        text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.length();
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    Token new0(String text, int line, int pos) { return new TLineComment(text, line, pos); }
    Token new1(String text, int line, int pos) { return new TTab(text, line, pos); }
    Token new2(int line, int pos) { return new TAssign(line, pos); }
    Token new3(int line, int pos) { return new TExclam(line, pos); }
    Token new4(int line, int pos) { return new TLPar(line, pos); }
    Token new5(int line, int pos) { return new TRPar(line, pos); }
    Token new6(int line, int pos) { return new TLBr(line, pos); }
    Token new7(int line, int pos) { return new TRBr(line, pos); }
    Token new8(int line, int pos) { return new TComma(line, pos); }
    Token new9(int line, int pos) { return new TQmark(line, pos); }
    Token new10(int line, int pos) { return new TGqmark(line, pos); }
    Token new11(int line, int pos) { return new TPlus(line, pos); }
    Token new12(int line, int pos) { return new TMinus(line, pos); }
    Token new13(int line, int pos) { return new TMult(line, pos); }
    Token new14(int line, int pos) { return new TDiv(line, pos); }
    Token new15(int line, int pos) { return new TMode(line, pos); }
    Token new16(int line, int pos) { return new TDmult(line, pos); }
    Token new17(int line, int pos) { return new TIf(line, pos); }
    Token new18(int line, int pos) { return new TElif(line, pos); }
    Token new19(int line, int pos) { return new TElse(line, pos); }
    Token new20(int line, int pos) { return new TWhile(line, pos); }
    Token new21(int line, int pos) { return new TFor(line, pos); }
    Token new22(int line, int pos) { return new TPrint(line, pos); }
    Token new23(int line, int pos) { return new TReturn(line, pos); }
    Token new24(int line, int pos) { return new TOpen(line, pos); }
    Token new25(int line, int pos) { return new TType(line, pos); }
    Token new26(int line, int pos) { return new TMax(line, pos); }
    Token new27(int line, int pos) { return new TMin(line, pos); }
    Token new28(int line, int pos) { return new TAssert(line, pos); }
    Token new29(int line, int pos) { return new TDictt(line, pos); }
    Token new30(int line, int pos) { return new TDef(line, pos); }
    Token new31(int line, int pos) { return new TNone(line, pos); }
    Token new32(int line, int pos) { return new TLeq(line, pos); }
    Token new33(int line, int pos) { return new TLess(line, pos); }
    Token new34(int line, int pos) { return new TGeq(line, pos); }
    Token new35(int line, int pos) { return new TGreat(line, pos); }
    Token new36(int line, int pos) { return new TNeq(line, pos); }
    Token new37(int line, int pos) { return new TEq(line, pos); }
    Token new38(int line, int pos) { return new TTrue(line, pos); }
    Token new39(int line, int pos) { return new TFalse(line, pos); }
    Token new40(int line, int pos) { return new TSemi(line, pos); }
    Token new41(int line, int pos) { return new TQuote(line, pos); }
    Token new42(String text, int line, int pos) { return new TBlank(text, line, pos); }
    Token new43(String text, int line, int pos) { return new TIntegerLiteral(text, line, pos); }
    Token new44(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    Token new45(String text, int line, int pos) { return new TStringLiteral(text, line, pos); }

    private int getChar() throws IOException
    {
        if(eof)
        {
            return -1;
        }

        int result = in.read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }
    }

    protected void unread(Token token) throws IOException
    {
        String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            in.unread(text.charAt(i));
        }

        pos = token.getPos() - 1;
        line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {35, 35, 7}, {37, 37, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {47, 47, 15}, {48, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {63, 63, 22}, {65, 77, 23}, {78, 78, 24}, {79, 90, 23}, {91, 91, 25}, {93, 93, 26}, {97, 97, 27}, {98, 99, 28}, {100, 100, 29}, {101, 101, 30}, {102, 102, 31}, {103, 104, 28}, {105, 105, 32}, {106, 108, 28}, {109, 109, 33}, {110, 110, 28}, {111, 111, 34}, {112, 112, 35}, {113, 113, 28}, {114, 114, 36}, {115, 115, 28}, {116, 116, 37}, {117, 118, 28}, {119, 119, 38}, {120, 122, 28}, },
            {},
            {},
            {},
            {},
            {{61, 61, 39}, },
            {{0, 9, 40}, {11, 12, 40}, {14, 33, 40}, {34, 34, 41}, {35, 127, 40}, },
            {{0, 9, 42}, {10, 10, 43}, {11, 12, 42}, {13, 13, 44}, {14, 127, 42}, },
            {},
            {},
            {},
            {{42, 42, 45}, },
            {},
            {},
            {},
            {},
            {{46, 46, 46}, {48, 57, 16}, },
            {},
            {},
            {{61, 61, 47}, },
            {{61, 61, 48}, },
            {{61, 61, 49}, },
            {},
            {{48, 57, 50}, {65, 90, 51}, {97, 122, 52}, },
            {{48, 90, -25}, {97, 110, 52}, {111, 111, 53}, {112, 122, 52}, },
            {},
            {},
            {{48, 90, -25}, {97, 114, 52}, {115, 115, 54}, {116, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 90, -25}, {97, 100, 52}, {101, 101, 55}, {102, 104, 52}, {105, 105, 56}, {106, 122, 52}, },
            {{48, 90, -25}, {97, 107, 52}, {108, 108, 57}, {109, 122, 52}, },
            {{48, 90, -25}, {97, 97, 58}, {98, 110, 52}, {111, 111, 59}, {112, 122, 52}, },
            {{48, 90, -25}, {97, 101, 52}, {102, 102, 60}, {103, 122, 52}, },
            {{48, 90, -25}, {97, 97, 61}, {98, 104, 52}, {105, 105, 62}, {106, 122, 52}, },
            {{48, 90, -25}, {97, 111, 52}, {112, 112, 63}, {113, 122, 52}, },
            {{48, 90, -25}, {97, 113, 52}, {114, 114, 64}, {115, 122, 52}, },
            {{48, 100, -31}, {101, 101, 65}, {102, 122, 52}, },
            {{48, 113, -37}, {114, 114, 66}, {115, 120, 52}, {121, 121, 67}, {122, 122, 52}, },
            {{48, 90, -25}, {97, 103, 52}, {104, 104, 68}, {105, 122, 52}, },
            {},
            {{0, 127, -8}, },
            {{0, 127, -8}, },
            {{0, 127, -9}, },
            {},
            {{10, 10, 69}, },
            {},
            {{48, 57, 70}, },
            {},
            {},
            {},
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 90, -25}, {97, 109, 52}, {110, 110, 71}, {111, 122, 52}, },
            {{48, 114, -29}, {115, 115, 72}, {116, 122, 52}, },
            {{48, 101, -34}, {102, 102, 73}, {103, 122, 52}, },
            {{48, 90, -25}, {97, 98, 52}, {99, 99, 74}, {100, 122, 52}, },
            {{48, 90, -25}, {97, 104, 52}, {105, 105, 75}, {106, 114, 52}, {115, 115, 76}, {116, 122, 52}, },
            {{48, 107, -32}, {108, 108, 77}, {109, 122, 52}, },
            {{48, 113, -37}, {114, 114, 78}, {115, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 90, -25}, {97, 119, 52}, {120, 120, 79}, {121, 122, 52}, },
            {{48, 109, -55}, {110, 110, 80}, {111, 122, 52}, },
            {{48, 100, -31}, {101, 101, 81}, {102, 122, 52}, },
            {{48, 104, -59}, {105, 105, 82}, {106, 122, 52}, },
            {{48, 90, -25}, {97, 115, 52}, {116, 116, 83}, {117, 122, 52}, },
            {{48, 90, -25}, {97, 116, 52}, {117, 117, 84}, {118, 122, 52}, },
            {{48, 111, -36}, {112, 112, 85}, {113, 122, 52}, },
            {{48, 104, -59}, {105, 105, 86}, {106, 122, 52}, },
            {},
            {{48, 57, 70}, },
            {{48, 100, -31}, {101, 101, 87}, {102, 122, 52}, },
            {{48, 100, -31}, {101, 101, 88}, {102, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 115, -67}, {116, 116, 89}, {117, 122, 52}, },
            {{48, 101, -34}, {102, 102, 90}, {103, 122, 52}, },
            {{48, 100, -31}, {101, 101, 91}, {102, 122, 52}, },
            {{48, 114, -29}, {115, 115, 92}, {116, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 109, -55}, {110, 110, 93}, {111, 122, 52}, },
            {{48, 109, -55}, {110, 110, 94}, {111, 122, 52}, },
            {{48, 116, -68}, {117, 117, 95}, {118, 122, 52}, },
            {{48, 100, -31}, {101, 101, 96}, {102, 122, 52}, },
            {{48, 100, -31}, {101, 101, 97}, {102, 122, 52}, },
            {{48, 107, -32}, {108, 108, 98}, {109, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 113, -37}, {114, 114, 99}, {115, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 100, -31}, {101, 101, 100}, {102, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 115, -67}, {116, 116, 101}, {117, 122, 52}, },
            {{48, 113, -37}, {114, 114, 102}, {115, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 100, -31}, {101, 101, 103}, {102, 122, 52}, },
            {{48, 115, -67}, {116, 116, 104}, {117, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 109, -55}, {110, 110, 105}, {111, 122, 52}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 1, 42, 42, 42, 3, 41, -1, 15, 4, 5, 13, 11, 8, 12, 14, 43, 40, 10, 33, 2, 35, 9, 44, 44, 6, 7, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 36, -1, 45, -1, 0, 0, 16, -1, 32, 37, 34, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 17, 44, 44, 44, 44, 44, 44, 44, 44, 0, 43, 44, 44, 30, 44, 44, 44, 44, 21, 26, 27, 44, 44, 44, 44, 44, 44, 31, 44, 29, 18, 19, 44, 24, 44, 44, 38, 25, 44, 44, 39, 22, 44, 20, 28, 23, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(int id)
        {
            this.id = id;
        }

        public int id()
        {
            return id;
        }
    }
}
